[2024-08-20T23:52:52.025+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-20T23:52:52.054+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: redfin_analytics_dag.tsk_load_redfin_data manual__2024-08-20T18:51:43.342772+00:00 [queued]>
[2024-08-20T23:52:52.201+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: redfin_analytics_dag.tsk_load_redfin_data manual__2024-08-20T18:51:43.342772+00:00 [queued]>
[2024-08-20T23:52:52.201+0500] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-20T23:52:52.236+0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): tsk_load_redfin_data> on 2024-08-20 18:51:43.342772+00:00
[2024-08-20T23:52:52.241+0500] {standard_task_runner.py:72} INFO - Started process 8062 to run task
[2024-08-20T23:52:52.248+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'redfin_analytics_dag', 'tsk_load_redfin_data', 'manual__2024-08-20T18:51:43.342772+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/redfin_analytics.py', '--cfg-path', '/tmp/tmpltm46u7m']
[2024-08-20T23:52:52.251+0500] {standard_task_runner.py:105} INFO - Job 10: Subtask tsk_load_redfin_data
[2024-08-20T23:52:52.333+0500] {task_command.py:467} INFO - Running <TaskInstance: redfin_analytics_dag.tsk_load_redfin_data manual__2024-08-20T18:51:43.342772+00:00 [running]> on host DESKTOP-2H02MT9.
[2024-08-20T23:52:52.459+0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rayyan' AIRFLOW_CTX_DAG_ID='redfin_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_load_redfin_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-20T18:51:43.342772+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-20T18:51:43.342772+00:00'
[2024-08-20T23:52:52.461+0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-20T23:52:52.462+0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-20T23:52:52.462+0500] {logging_mixin.py:190} INFO - Current task name:tsk_load_redfin_data state:running start_date:2024-08-20 18:52:52.054728+00:00
[2024-08-20T23:52:52.463+0500] {logging_mixin.py:190} INFO - Dag name:redfin_analytics_dag and current dag run status:running
[2024-08-20T23:52:52.463+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-20T23:52:52.471+0500] {logging_mixin.py:190} INFO - /home/rayyan/airflow/data/output/redfin_data_20082024235232
[2024-08-20T23:52:52.475+0500] {logging_mixin.py:190} INFO - in transform 2
[2024-08-20T23:52:58.891+0500] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/rayyan/airflow/dags/redfin_analytics.py", line 133, in load_raw_Data_To_bucket
    s3_client.put_object(Bucket='storerawdatayml', Key=object_key, Body=data)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
[2024-08-20T23:52:58.902+0500] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-20T23:52:58.903+0500] {logging_mixin.py:190} INFO - Task start:2024-08-20 18:52:52.054728+00:00 end:2024-08-20 18:52:58.901317+00:00 duration:6.846589
[2024-08-20T23:52:58.903+0500] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): tsk_load_redfin_data> dag:<DAG: redfin_analytics_dag> dagrun:<DagRun redfin_analytics_dag @ 2024-08-20 18:51:43.342772+00:00: manual__2024-08-20T18:51:43.342772+00:00, state:running, queued_at: 2024-08-20 18:51:43.379973+00:00. externally triggered: True>
[2024-08-20T23:52:58.904+0500] {logging_mixin.py:190} INFO - Failure caused by An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
[2024-08-20T23:52:58.904+0500] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=redfin_analytics_dag, task_id=tsk_load_redfin_data, run_id=manual__2024-08-20T18:51:43.342772+00:00, execution_date=20240820T185143, start_date=20240820T185252, end_date=20240820T185258
[2024-08-20T23:52:58.933+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-20T23:52:58.934+0500] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task tsk_load_redfin_data (An error occurred (AccessDenied) when calling the PutObject operation: Access Denied; 8062)
Traceback (most recent call last):
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/rayyan/airflow/dags/redfin_analytics.py", line 133, in load_raw_Data_To_bucket
    s3_client.put_object(Bucket='storerawdatayml', Key=object_key, Body=data)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
[2024-08-20T23:52:58.945+0500] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-20T23:52:58.972+0500] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-20T23:52:58.973+0500] {local_task_job_runner.py:240} INFO - ::endgroup::
