[2024-08-20T23:41:01.518+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-20T23:41:01.539+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: redfin_analytics_dag.tsk_extract_redfin_data manual__2024-08-20T18:40:55.549248+00:00 [queued]>
[2024-08-20T23:41:01.682+0500] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: redfin_analytics_dag.tsk_extract_redfin_data manual__2024-08-20T18:40:55.549248+00:00 [queued]>
[2024-08-20T23:41:01.683+0500] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-08-20T23:41:01.703+0500] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): tsk_extract_redfin_data> on 2024-08-20 18:40:55.549248+00:00
[2024-08-20T23:41:01.707+0500] {standard_task_runner.py:72} INFO - Started process 7538 to run task
[2024-08-20T23:41:01.713+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'redfin_analytics_dag', 'tsk_extract_redfin_data', 'manual__2024-08-20T18:40:55.549248+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/redfin_analytics.py', '--cfg-path', '/tmp/tmppbo8x1yx']
[2024-08-20T23:41:01.714+0500] {standard_task_runner.py:105} INFO - Job 5: Subtask tsk_extract_redfin_data
[2024-08-20T23:41:01.774+0500] {task_command.py:467} INFO - Running <TaskInstance: redfin_analytics_dag.tsk_extract_redfin_data manual__2024-08-20T18:40:55.549248+00:00 [running]> on host DESKTOP-2H02MT9.
[2024-08-20T23:41:01.863+0500] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Abdullah Khan' AIRFLOW_CTX_DAG_ID='redfin_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_extract_redfin_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-20T18:40:55.549248+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-20T18:40:55.549248+00:00'
[2024-08-20T23:41:01.865+0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-08-20T23:41:01.865+0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-08-20T23:41:01.865+0500] {logging_mixin.py:190} INFO - Current task name:tsk_extract_redfin_data state:running start_date:2024-08-20 18:41:01.540068+00:00
[2024-08-20T23:41:01.866+0500] {logging_mixin.py:190} INFO - Dag name:redfin_analytics_dag and current dag run status:running
[2024-08-20T23:41:01.866+0500] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-20T23:41:01.867+0500] {logging_mixin.py:190} INFO - in the extract func
[2024-08-20T23:41:46.544+0500] {logging_mixin.py:190} INFO - suc 1
[2024-08-20T23:41:46.558+0500] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/rayyan/airflow/dags/redfin_analytics.py", line 32, in extract_data
    df.to_csv(f"{output_file_path}.csv", index=False)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/opt/airflow/data/output'
[2024-08-20T23:41:46.584+0500] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-08-20T23:41:46.585+0500] {logging_mixin.py:190} INFO - Task start:2024-08-20 18:41:01.540068+00:00 end:2024-08-20 18:41:46.582939+00:00 duration:45.042871
[2024-08-20T23:41:46.585+0500] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): tsk_extract_redfin_data> dag:<DAG: redfin_analytics_dag> dagrun:<DagRun redfin_analytics_dag @ 2024-08-20 18:40:55.549248+00:00: manual__2024-08-20T18:40:55.549248+00:00, state:running, queued_at: 2024-08-20 18:40:55.571212+00:00. externally triggered: True>
[2024-08-20T23:41:46.586+0500] {logging_mixin.py:190} INFO - Failure caused by Cannot save file into a non-existent directory: '/opt/airflow/data/output'
[2024-08-20T23:41:46.587+0500] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=redfin_analytics_dag, task_id=tsk_extract_redfin_data, run_id=manual__2024-08-20T18:40:55.549248+00:00, execution_date=20240820T184055, start_date=20240820T184101, end_date=20240820T184146
[2024-08-20T23:41:46.616+0500] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-20T23:41:46.617+0500] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task tsk_extract_redfin_data (Cannot save file into a non-existent directory: '/opt/airflow/data/output'; 7538)
Traceback (most recent call last):
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/rayyan/airflow/dags/redfin_analytics.py", line 32, in extract_data
    df.to_csv(f"{output_file_path}.csv", index=False)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/rayyan/redfin_venv/lib/python3.10/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/opt/airflow/data/output'
[2024-08-20T23:41:46.664+0500] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-20T23:41:46.706+0500] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-20T23:41:46.716+0500] {local_task_job_runner.py:240} INFO - ::endgroup::
